[phases.setup]
nixPkgs = ["nodejs_20", "python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = [
    "npm install",
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate && pip install -r python-requirements.txt"
]

[phases.build]
cmds = ["npm install"]

[start]
cmd = ". /opt/venv/bin/activate && node server.js"
